### ISSUE TITLE
feat-> eat

### ISSUE THREAD

**Issue by imchao9** [milobluebell/auto-release-shit#1]
![image](https://user-images.githubusercontent.com/6490080/68211700-023aad80-0013-11ea-9d90-ef3a4ac382a2.png)

**Comment by milobluebell** [comment]
因为 feat()后缺少冒号，是不符合angular commit规范的。已经添加了对 「feat() add something」的兼容。现在会以第一个空格作为key和value的分割。
但还是建议文华，按照规范提交commit message。

enhanced in v1.1.1
