### ISSUE TITLE
[feature]增加一个复制按钮和测试对接人可以编辑

### ISSUE THREAD

**Issue by WzFFzW** [milobluebell/auto-release-shit#2]
功能点： 1.现在需要用户手动复制，增加一个复制按钮会更加的好
2. 测试对接人并不一是固定，可以有默认值，但是最好可以编辑

**Comment by milobluebell** [comment]
已经加入该功能，多谢反馈。  @WzFFzW 更新到1.1.2版本后查看该需求。

enhanced in v1.1.2
